version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: "build"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
