version: "3"

services:
  next-app:
    build:
      context: ./
      dockerfile: Dockerfile
    pull_policy: build
    container_name: client-portfolio-next
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
    ports:
      - '3000:3000'
    networks:
      - app

networks:
  app: