version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    pull_policy: build
    ports:
      - "3000:3000"